times = ["Atletico Mineiro",
          "Atletico Paranaense",
          "Avai",
          "Chapecoense",
          "Corinthians",
          "Coritiba",
          "Cruzeiro",
          "Figueirense",
          "Flamengo",
          "Fluminense",
          "Goiais",
          "Gremio",
          "Internacional",
          "Joinville",
          "Palmeiras",
          "Ponte Preta",
          "Santos",
          "São Paulo",
          "Sport",
          "Vasco"]



timesFox = ["atletico-mg",
          "atletico-pr",
          "avai",
          "chapecoense",
          "corinthians",
          "coritiba",
          "cruzeiro",
          "figueirense",
          "flamengo",
          "fluminense",
          "goiais",
          "gremio",
          "internacional",
          "joinville",
          "palmeiras",
          "Ponte%20Preta",
          "santos",
          "São%20Paulo",
          "sport",
          "vasco"]

timesUol = ["atleticomg",
          "atleticopr",
          "avai",
          "chapecoense",
          "corinthians",
          "coritiba",
          "cruzeiro",
          "figueirense",
          "flamengo",
          "fluminense",
          "goiais",
          "gremio",
          "internacional",
          "joinville",
          "palmeiras",
          "pontepreta",
          "santos",
          "saopaulo",
          "sport",
          "vasco"]

timesGlobo = ["atletico-mg",
          "atletico-pr",
          "avai",
          "chapecoense",
          "corinthians",
          "coritiba",
          "cruzeiro",
          "figueirense",
          "flamengo",
          "fluminense",
          "goiais",
          "gremio",
          "internacional",
          "joinville",
          "palmeiras",
          "pontePreta",
          "santos",
          "sao-paulo",
          "sport",
          "vasco"]

/// time: [facebook,instagram,twitter];
jsonT = [["42462502551","atletico","atletico"],
       ["181724431849551","atleticoparanaense","atleticopr"],
       ["186096768095645","avaifc","avaifc"],
       ["540753042620453","chapecoensereal","chapecoensereal"],
       ["132769576762243","corinthians","corinthians"],
       ["149928188434825","coritibaoficial","coritiba"],
       ["144767812249202","cruzeiro","cruzeiro"],
       ["144702065554485","figueirenseoficial","figueirensefc"],
       ["204073162943401","flamengo","flamengo"],
       ["159225040801899","fluminensefc","fluminensefc"],
       ["121689147913563","goiasoficial","goiasec_oficial"],
       ["242811539084237","gremiooficial","gremiooficial"],
       ["176934912345768","scinternacionaloficial","scinternacional"],
       ["141350739273316","jec_oficial","jec_online"],
       ["344366709466","sepalmeiras","sepalmeiras"],
       ["156238824423790","pontepretaoficial","aapp_oficial"],
       ["101402899928278","santosfc","santosfc"],
       ["8253854419","saopaulofc","saopaulofc"],
       ["104306929602404","sportrecife","sportrecife"],
       ["455514190453","vascodagama","vascodagama"]
]